import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layout/Navbar';
import AuroraBackground from '@/components/layout/AuroraBackground'; // นำพื้นหลังมาใช้ที่นี่
import Footer from '@/components/layout/Footer';
import NextAuthProvider from '@/providers/NextAuthProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'MindFlow | AI Meditation',
  description: 'Personalized mindfulness generated by AI',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className="h-full" suppressHydrationWarning> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full font-sans`}
        suppressHydrationWarning /* Add this here */
      >
        <AuroraBackground>
          <NextAuthProvider session={session}>
            <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-1 flex flex-col pt-20"> 
              {children}
            </main>
          </div>
          </NextAuthProvider>
          
        </AuroraBackground>
      </body>
    </html>
  );
}